import time

from naoqi import ALProxy
from pepper_robots import Robot, PepperConfiguration, PepperNames


class Laser:
    def __init__(self, robot, config):
        self.robot = robot
        self.tts = ALProxy("ALTextToSpeech", config.Ip, config.Port)

    def run_demo(self):
        print("Raw Laser Shovel Data: ")
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Front/Shovel/Seg01/X/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Front/Shovel/Seg01/Y/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Front/Shovel/Seg02/X/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Front/Shovel/Seg02/Y/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Front/Shovel/Seg03/X/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Front/Shovel/Seg03/Y/Sensor/Value')
        print(data)

        print("Vertical right data: ")
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Front/Vertical/Right/Seg01/X/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Front/Vertical/Right/Seg01/Y/Sensor/Value')
        print(data)

        print("Vertical right data: ")
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Front/Vertical/Left/Seg01/X/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Front/Vertical/Left/Seg01/Y/Sensor/Value')
        print(data)

        print("Surrounding Front: ")
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Front/Reg/Status/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Front/Reg/BoardTemp/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Front/Reg/FrameCount/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Front/Reg/AssertFailCount/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Front/Reg/RunMode/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Front/Reg/CalibrDataVer/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Front/Reg/OperationMode/Actuator/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Front/Reg/OperationMode/Sensor/Value')
        print(data)

        print("Surrounding Horizontal obstacle data: ")
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Front/Horizontal/Seg01/X/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Front/Horizontal/Seg01/Y/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Front/Horizontal/Seg02/X/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Front/Horizontal/Seg02/Y/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Front/Horizontal/Seg03/X/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Front/Horizontal/Seg03/Y/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Front/Horizontal/Seg04/X/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Front/Horizontal/Seg04/Y/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Front/Horizontal/Seg05/X/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Front/Horizontal/Seg05/Y/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Front/Horizontal/Seg06/X/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Front/Horizontal/Seg06/Y/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Front/Horizontal/Seg07/X/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Front/Horizontal/Seg07/Y/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Front/Horizontal/Seg08/X/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Front/Horizontal/Seg08/Y/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Front/Horizontal/Seg09/X/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Front/Horizontal/Seg09/Y/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Front/Horizontal/Seg10/X/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Front/Horizontal/Seg10/Y/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Front/Horizontal/Seg11/X/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Front/Horizontal/Seg11/Y/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Front/Horizontal/Seg12/X/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Front/Horizontal/Seg12/Y/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Front/Horizontal/Seg13/X/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Front/Horizontal/Seg13/Y/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Front/Horizontal/Seg14/X/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Front/Horizontal/Seg14/Y/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Front/Horizontal/Seg15/X/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Front/Horizontal/Seg15/Y/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Front/Horizontal/Reg/DataStatus/Sensor/Value')
        print(data)
        # data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Front/Horizontal/Reg/Time/Sensor/Value')
        # print(data)

        print("Surrounding Horizontal uncertain obstacle data: ")
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Front/UncertainObstacle/Seg01/X/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Front/UncertainObstacle/Seg01/Y/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Front/UncertainObstacle/Seg02/X/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Front/UncertainObstacle/Seg02/Y/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Front/UncertainObstacle/Seg03/X/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Front/UncertainObstacle/Seg03/Y/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Front/UncertainObstacle/Seg04/X/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Front/UncertainObstacle/Seg04/Y/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Front/UncertainObstacle/Seg05/X/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Front/UncertainObstacle/Seg05/Y/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Front/UncertainObstacle/Seg06/X/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Front/UncertainObstacle/Seg06/Y/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Front/UncertainObstacle/Seg07/X/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Front/UncertainObstacle/Seg07/Y/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Front/UncertainObstacle/Seg08/X/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Front/UncertainObstacle/Seg08/Y/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Front/UncertainObstacle/Seg09/X/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Front/UncertainObstacle/Seg09/Y/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Front/UncertainObstacle/Seg10/X/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Front/UncertainObstacle/Seg10/Y/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Front/UncertainObstacle/Seg11/X/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Front/UncertainObstacle/Seg11/Y/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Front/UncertainObstacle/Seg12/X/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Front/UncertainObstacle/Seg12/Y/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Front/UncertainObstacle/Seg13/X/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Front/UncertainObstacle/Seg13/Y/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Front/UncertainObstacle/Seg14/X/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Front/UncertainObstacle/Seg14/Y/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Front/UncertainObstacle/Seg15/X/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Front/UncertainObstacle/Seg15/Y/Sensor/Value')
        print(data)
        # data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Front/UncertainObstacle/Reg/DataStatus/Sensor/Value')
        # print(data)
        # data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Front/UncertainObstacle/Reg/Time/Sensor/Value')
        # print(data)


        print("Surrounding Horizontal annoying reflection data: ")
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Front/AnnoyingReflection/Seg01/X/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Front/AnnoyingReflection/Seg01/Y/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Front/AnnoyingReflection/Seg02/X/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Front/AnnoyingReflection/Seg02/Y/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Front/AnnoyingReflection/Seg03/X/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Front/AnnoyingReflection/Seg03/Y/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Front/AnnoyingReflection/Seg04/X/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Front/AnnoyingReflection/Seg04/Y/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Front/AnnoyingReflection/Seg05/X/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Front/AnnoyingReflection/Seg05/Y/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Front/AnnoyingReflection/Seg06/X/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Front/AnnoyingReflection/Seg06/Y/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Front/AnnoyingReflection/Seg07/X/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Front/AnnoyingReflection/Seg07/Y/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Front/AnnoyingReflection/Seg08/X/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Front/AnnoyingReflection/Seg08/Y/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Front/AnnoyingReflection/Seg09/X/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Front/AnnoyingReflection/Seg09/Y/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Front/AnnoyingReflection/Seg10/X/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Front/AnnoyingReflection/Seg10/Y/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Front/AnnoyingReflection/Seg11/X/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Front/AnnoyingReflection/Seg11/Y/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Front/AnnoyingReflection/Seg12/X/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Front/AnnoyingReflection/Seg12/Y/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Front/AnnoyingReflection/Seg13/X/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Front/AnnoyingReflection/Seg13/Y/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Front/AnnoyingReflection/Seg14/X/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Front/AnnoyingReflection/Seg14/Y/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Front/AnnoyingReflection/Seg15/X/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Front/AnnoyingReflection/Seg15/Y/Sensor/Value')
        print(data)
        # data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Front/AnnoyingReflection/Reg/DataStatus/Sensor/Value')
        # print(data)
        # data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Front/AnnoyingReflection/Reg/Time/Sensor/Value')
        # print(data)


        print("Surrounding Left: ")
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Left/Reg/Status/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Left/Reg/BoardTemp/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Left/Reg/FrameCount/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Left/Reg/AssertFailCount/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Left/Reg/RunMode/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Left/Reg/CalibrDataVer/Sensor/Value')
        print(data)

        print("Left Horizontal obstacle data: ")
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Left/Horizontal/Seg01/X/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Left/Horizontal/Seg01/Y/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Left/Horizontal/Seg02/X/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Left/Horizontal/Seg02/Y/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Left/Horizontal/Seg03/X/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Left/Horizontal/Seg03/Y/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Left/Horizontal/Seg04/X/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Left/Horizontal/Seg04/Y/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Left/Horizontal/Seg05/X/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Left/Horizontal/Seg05/Y/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Left/Horizontal/Seg06/X/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Left/Horizontal/Seg06/Y/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Left/Horizontal/Seg07/X/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Left/Horizontal/Seg07/Y/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Left/Horizontal/Seg08/X/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Left/Horizontal/Seg08/Y/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Left/Horizontal/Seg09/X/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Left/Horizontal/Seg09/Y/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Left/Horizontal/Seg10/X/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Left/Horizontal/Seg10/Y/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Left/Horizontal/Seg11/X/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Left/Horizontal/Seg11/Y/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Left/Horizontal/Seg12/X/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Left/Horizontal/Seg12/Y/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Left/Horizontal/Seg13/X/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Left/Horizontal/Seg13/Y/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Left/Horizontal/Seg14/X/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Left/Horizontal/Seg14/Y/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Left/Horizontal/Seg15/X/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Left/Horizontal/Seg15/Y/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Left/Horizontal/Reg/DataStatus/Sensor/Value')
        print(data)
        # data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Left/Horizontal/Reg/Time/Sensor/Value')
        # print(data)

        print("Left Horizontal uncertain obstacle data: ")
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Left/UncertainObstacle/Seg01/X/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Left/UncertainObstacle/Seg01/Y/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Left/UncertainObstacle/Seg02/X/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Left/UncertainObstacle/Seg02/Y/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Left/UncertainObstacle/Seg03/X/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Left/UncertainObstacle/Seg03/Y/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Left/UncertainObstacle/Seg04/X/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Left/UncertainObstacle/Seg04/Y/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Left/UncertainObstacle/Seg05/X/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Left/UncertainObstacle/Seg05/Y/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Left/UncertainObstacle/Seg06/X/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Left/UncertainObstacle/Seg06/Y/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Left/UncertainObstacle/Seg07/X/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Left/UncertainObstacle/Seg07/Y/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Left/UncertainObstacle/Seg08/X/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Left/UncertainObstacle/Seg08/Y/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Left/UncertainObstacle/Seg09/X/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Left/UncertainObstacle/Seg09/Y/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Left/UncertainObstacle/Seg10/X/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Left/UncertainObstacle/Seg10/Y/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Left/UncertainObstacle/Seg11/X/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Left/UncertainObstacle/Seg11/Y/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Left/UncertainObstacle/Seg12/X/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Left/UncertainObstacle/Seg12/Y/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Left/UncertainObstacle/Seg13/X/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Left/UncertainObstacle/Seg13/Y/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Left/UncertainObstacle/Seg14/X/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Left/UncertainObstacle/Seg14/Y/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Left/UncertainObstacle/Seg15/X/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Left/UncertainObstacle/Seg15/Y/Sensor/Value')
        print(data)
        # data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Left/UncertainObstacle/Reg/DataStatus/Sensor/Value')
        # print(data)
        # data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Left/UncertainObstacle/Reg/Time/Sensor/Value')
        # print(data)


        print("Left Horizontal annoying reflection data: ")
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Left/AnnoyingReflection/Seg01/X/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Left/AnnoyingReflection/Seg01/Y/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Left/AnnoyingReflection/Seg02/X/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Left/AnnoyingReflection/Seg02/Y/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Left/AnnoyingReflection/Seg03/X/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Left/AnnoyingReflection/Seg03/Y/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Left/AnnoyingReflection/Seg04/X/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Left/AnnoyingReflection/Seg04/Y/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Left/AnnoyingReflection/Seg05/X/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Left/AnnoyingReflection/Seg05/Y/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Left/AnnoyingReflection/Seg06/X/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Left/AnnoyingReflection/Seg06/Y/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Left/AnnoyingReflection/Seg07/X/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Left/AnnoyingReflection/Seg07/Y/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Left/AnnoyingReflection/Seg08/X/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Left/AnnoyingReflection/Seg08/Y/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Left/AnnoyingReflection/Seg09/X/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Left/AnnoyingReflection/Seg09/Y/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Left/AnnoyingReflection/Seg10/X/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Left/AnnoyingReflection/Seg10/Y/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Left/AnnoyingReflection/Seg11/X/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Left/AnnoyingReflection/Seg11/Y/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Left/AnnoyingReflection/Seg12/X/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Left/AnnoyingReflection/Seg12/Y/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Left/AnnoyingReflection/Seg13/X/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Left/AnnoyingReflection/Seg13/Y/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Left/AnnoyingReflection/Seg14/X/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Left/AnnoyingReflection/Seg14/Y/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Left/AnnoyingReflection/Seg15/X/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Left/AnnoyingReflection/Seg15/Y/Sensor/Value')
        print(data)
        # data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Left/AnnoyingReflection/Reg/DataStatus/Sensor/Value')
        # print(data)
        # data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Left/AnnoyingReflection/Reg/Time/Sensor/Value')
        # print(data)

        print("Surrounding Right: ")
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Right/Reg/Status/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Right/Reg/BoardTemp/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Right/Reg/FrameCount/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Right/Reg/AssertFailCount/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Right/Reg/RunMode/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Right/Reg/CalibrDataVer/Sensor/Value')
        print(data)

        print("Right Horizontal obstacle data: ")
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Right/Horizontal/Seg01/X/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Right/Horizontal/Seg01/Y/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Right/Horizontal/Seg02/X/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Right/Horizontal/Seg02/Y/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Right/Horizontal/Seg03/X/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Right/Horizontal/Seg03/Y/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Right/Horizontal/Seg04/X/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Right/Horizontal/Seg04/Y/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Right/Horizontal/Seg05/X/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Right/Horizontal/Seg05/Y/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Right/Horizontal/Seg06/X/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Right/Horizontal/Seg06/Y/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Right/Horizontal/Seg07/X/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Right/Horizontal/Seg07/Y/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Right/Horizontal/Seg08/X/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Right/Horizontal/Seg08/Y/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Right/Horizontal/Seg09/X/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Right/Horizontal/Seg09/Y/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Right/Horizontal/Seg10/X/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Right/Horizontal/Seg10/Y/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Right/Horizontal/Seg11/X/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Right/Horizontal/Seg11/Y/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Right/Horizontal/Seg12/X/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Right/Horizontal/Seg12/Y/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Right/Horizontal/Seg13/X/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Right/Horizontal/Seg13/Y/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Right/Horizontal/Seg14/X/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Right/Horizontal/Seg14/Y/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Right/Horizontal/Seg15/X/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Right/Horizontal/Seg15/Y/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Right/Horizontal/Reg/DataStatus/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Right/Horizontal/Reg/Time/Sensor/Value')
        print(data)

        print("Right Horizontal uncertain obstacle data: ")
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Right/UncertainObstacle/Seg01/X/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Right/UncertainObstacle/Seg01/Y/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Right/UncertainObstacle/Seg02/X/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Right/UncertainObstacle/Seg02/Y/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Right/UncertainObstacle/Seg03/X/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Right/UncertainObstacle/Seg03/Y/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Right/UncertainObstacle/Seg04/X/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Right/UncertainObstacle/Seg04/Y/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Right/UncertainObstacle/Seg05/X/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Right/UncertainObstacle/Seg05/Y/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Right/UncertainObstacle/Seg06/X/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Right/UncertainObstacle/Seg06/Y/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Right/UncertainObstacle/Seg07/X/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Right/UncertainObstacle/Seg07/Y/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Right/UncertainObstacle/Seg08/X/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Right/UncertainObstacle/Seg08/Y/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Right/UncertainObstacle/Seg09/X/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Right/UncertainObstacle/Seg09/Y/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Right/UncertainObstacle/Seg10/X/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Right/UncertainObstacle/Seg10/Y/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Right/UncertainObstacle/Seg11/X/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Right/UncertainObstacle/Seg11/Y/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Right/UncertainObstacle/Seg12/X/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Right/UncertainObstacle/Seg12/Y/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Right/UncertainObstacle/Seg13/X/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Right/UncertainObstacle/Seg13/Y/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Right/UncertainObstacle/Seg14/X/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Right/UncertainObstacle/Seg14/Y/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Right/UncertainObstacle/Seg15/X/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Right/UncertainObstacle/Seg15/Y/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Right/UncertainObstacle/Reg/DataStatus/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Right/UncertainObstacle/Reg/Time/Sensor/Value')
        print(data)


        print("Right Horizontal annoying reflection data: ")
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Right/AnnoyingReflection/Seg01/X/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Right/AnnoyingReflection/Seg01/Y/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Right/AnnoyingReflection/Seg02/X/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Right/AnnoyingReflection/Seg02/Y/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Right/AnnoyingReflection/Seg03/X/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Right/AnnoyingReflection/Seg03/Y/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Right/AnnoyingReflection/Seg04/X/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Right/AnnoyingReflection/Seg04/Y/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Right/AnnoyingReflection/Seg05/X/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Right/AnnoyingReflection/Seg05/Y/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Right/AnnoyingReflection/Seg06/X/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Right/AnnoyingReflection/Seg06/Y/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Right/AnnoyingReflection/Seg07/X/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Right/AnnoyingReflection/Seg07/Y/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Right/AnnoyingReflection/Seg08/X/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Right/AnnoyingReflection/Seg08/Y/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Right/AnnoyingReflection/Seg09/X/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Right/AnnoyingReflection/Seg09/Y/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Right/AnnoyingReflection/Seg10/X/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Right/AnnoyingReflection/Seg10/Y/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Right/AnnoyingReflection/Seg11/X/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Right/AnnoyingReflection/Seg11/Y/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Right/AnnoyingReflection/Seg12/X/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Right/AnnoyingReflection/Seg12/Y/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Right/AnnoyingReflection/Seg13/X/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Right/AnnoyingReflection/Seg13/Y/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Right/AnnoyingReflection/Seg14/X/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Right/AnnoyingReflection/Seg14/Y/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Right/AnnoyingReflection/Seg15/X/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Right/AnnoyingReflection/Seg15/Y/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Right/AnnoyingReflection/Reg/DataStatus/Sensor/Value')
        print(data)
        data = self.robot.ALMemory.getData('Device/SubDeviceList/Platform/LaserSensor/Right/AnnoyingReflection/Reg/Time/Sensor/Value')
        print(data)

        time.sleep(2)


if __name__ == '__main__':
    config = PepperConfiguration(PepperNames.Pale)
    robot = Robot(config, reset=True)
    laser = Laser(robot, config)
    laser.run_demo()

